spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

# JWT Configuration
jwt.secret=ConfigServerHRMSSecretKeyForJWTTokenGenerationAndValidation1234567890
jwt.expiration=86400000

# Gateway Routes Configuration (Direct URLs - No Eureka)
# Employee Service Routes
spring.cloud.gateway.mvc.routes[0].id=employee-service
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8088
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/employees/**

# Attendance Service Routes
spring.cloud.gateway.mvc.routes[1].id=attendance-service
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8085
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/attendance/**

# Leave Service Routes
spring.cloud.gateway.mvc.routes[2].id=leave-service
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8087
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/leaves/**

# Payroll Service Routes
spring.cloud.gateway.mvc.routes[3].id=payroll-service
spring.cloud.gateway.mvc.routes[3].uri=http://localhost:8086
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/payroll/**

# Mapping Service Routes
spring.cloud.gateway.mvc.routes[4].id=mapping-service
spring.cloud.gateway.mvc.routes[4].uri=http://localhost:8089
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/mapping/**

# Report Service Routes
spring.cloud.gateway.mvc.routes[5].id=report-service
spring.cloud.gateway.mvc.routes[5].uri=http://localhost:8090
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/reports/**

# Leave-holiday Service Routes
spring.cloud.gateway.mvc.routes[6].id=leave-service-holiday
spring.cloud.gateway.mvc.routes[6].uri=http://localhost:8087
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/api/holidays/**

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=DEBUG
