spring.application.name=leaveService

# MySQL DB Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/leave_hrm_db
spring.datasource.username=root
spring.datasource.password=root
server.port=8087

# Optional: Specify driver class (usually auto-detected)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (Hibernate) config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Leave types and default counts (format: TYPE:DEFAULT_COUNT)
hrm.leave.types=SICK:50,PAID:2,CASUAL:7,UNPAID:365,WFH:365

# Monthly paid leave limit
hrm.leave.monthly.paid.limit=2


hrm.holidays=2025-01-26,2025-03-29,2025-04-14,2025-05-01,2025-08-15,2025-10-02,2025-11-01,2025-12-25


